### ISSUE TITLE
NoClassDefFoundError: org/eclipse/swt/widgets/Display after upgrade of CDT from 2023-12 to 2024-03

### ISSUE THREAD

**Issue by gtjoseph** [eclipse-cdt/cdt#739]
**Describe the bug**
After upgrading 4 different, otherwise working, CDT-2023-12 installations, attempting to open any editor results in...

```
java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Display
	at org.eclipse.jface.text.rules.Token.prepareData(Token.java:82)
	at org.eclipse.jface.text.rules.Token.<init>(Token.java:83)
	at org.eclipse.cdt.internal.ui.text.TokenStore.addToken(TokenStore.java:104)
	at org.eclipse.cdt.internal.ui.text.TokenStore.<init>(TokenStore.java:74)
```
Full log attached below

**To Reproduce**
Take a working CDT-2023-12 and upgrade via "Check for updates".
Agree to upgrade existing workspace.
Try to open an editor.

This can't be reproduced on a fresh CDT-2023-12 install so it must have to do with the workspace or other settings, plugins, etc.

**Expected behavior**
The update completes and editors open.

**Screenshots**

![image](https://github.com/eclipse-cdt/cdt/assets/1205666/ef42d00e-79e9-417d-ada2-da5a9401e19d)

**Version Information (please complete the following information):**
Fedora 39 Workstation XFCE
Kernel  6.7.9-200.fc39.x86_64

Eclipse IDE for C/C++ Developers (includes Incubating components)
Version: 2024-03 (4.31.0)
Build id: 20240307-1437

Eclipse CDT	C/C++ Development Platform	11.5.0.202403041627	org.eclipse.cdt.platform

**Additional context**
[log.txt](https://github.com/eclipse-cdt/cdt/files/14628691/log.txt)

This issue has NOT happened upgrading any JEE-2023-12 installations.
